# ResidualAnalysisEngine.cs komplett neu schreiben
# Ausfuehren: powershell -ExecutionPolicy Bypass -File .\fix-residual-engine.ps1

$targetFile = "C:\Projekte\ZeroTrace\src\ZeroTrace.Core\Analysis\ResidualAnalysisEngine.cs"

# Gesamten Code als Array von Zeilen definieren (vermeidet Escaping-Probleme)
$lines = @(
    'using System.Runtime.Versioning;',
    'using System.Text.RegularExpressions;',
    'using Microsoft.Win32;',
    'using ZeroTrace.Core.Models;',
    'using ZeroTrace.Core.Logging;',
    '',
    'namespace ZeroTrace.Core.Analysis;',
    '',
    'public sealed class ScanProgressEventArgs : EventArgs',
    '{',
    '    public required string CurrentAreaName { get; init; }',
    '    public required string CurrentPath { get; init; }',
    '    public required int TotalAreas { get; init; }',
    '    public required int CompletedAreas { get; init; }',
    '    public required int ItemsFoundSoFar { get; init; }',
    '    public int PercentComplete => TotalAreas == 0 ? 0 : (int)(CompletedAreas * 100.0 / TotalAreas);',
    '}',
    '',
    '[SupportedOSPlatform("windows")]',
    'public sealed class ResidualAnalysisEngine',
    '{',
    '    private readonly IZeroTraceLogger _logger;',
    '',
    '    private static readonly HashSet<string> ProtectedPaths = new(StringComparer.OrdinalIgnoreCase)',
    '    {',
    '        @"C:\Windows", @"C:\Windows\System32", @"C:\Windows\SysWOW64",',
    '        @"C:\Windows\WinSxS", @"C:\Windows\Fonts", @"C:\Windows\Installer",',
    '        @"C:\Program Files\Windows Defender", @"C:\Program Files\Windows NT",',
    '        @"C:\Program Files\WindowsApps", @"C:\ProgramData\Microsoft", @"C:\ProgramData\Windows",',
    '    };',
    '',
    '    private static readonly string[] ProtectedRegistryPrefixes =',
    '    [',
    '        @"HKEY_LOCAL_MACHINE\SYSTEM",',
    '        @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion",',
    '        @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT",',
    '        @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography",',
    '        @"HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID",',
    '    ];',
    '',
    '    private static readonly HashSet<string> StopWords = new(StringComparer.OrdinalIgnoreCase)',
    '    {',
    '        "The", "Inc", "Ltd", "LLC", "Corp", "Corporation", "Software", "Microsoft",',
    '        "Windows", "System", "System32", "Update", "Setup", "Install", "Uninstall",',
    '        "Common", "Shared", "Data", "Files", "Program", "App", "Application",',
    '        "Tools", "Utility", "x86", "x64", "amd64", "arm64",',
    '    };',
    '',
    '    public event EventHandler<ScanProgressEventArgs>? ProgressChanged;',
    '',
    '    public ResidualAnalysisEngine(IZeroTraceLogger logger)',
    '    {',
    '        _logger = logger ?? throw new ArgumentNullException(nameof(logger));',
    '    }',
    '',
    '    public async Task<IReadOnlyList<ResidualItem>> ScanAsync(',
    '        InstalledProgram program, CancellationToken cancellationToken = default)',
    '    {',
    '        _logger.Info("Residual-Scan: " + program.DisplayName);',
    '        var searchTerms = BuildSearchTerms(program);',
    '        _logger.Info("  Suchbegriffe: [" + string.Join(", ", searchTerms) + "]");',
    '',
    '        if (searchTerms.Count == 0)',
    '        {',
    '            _logger.Warning("  Keine Suchbegriffe.");',
    '            return Array.Empty<ResidualItem>();',
    '        }',
    '',
    '        var scanAreas = BuildScanAreas(program);',
    '        var allResults = new List<ResidualItem>();',
    '        int completedAreas = 0;',
    '',
    '        foreach (var area in scanAreas)',
    '        {',
    '            cancellationToken.ThrowIfCancellationRequested();',
    '            ReportProgress(area.Name, area.BasePath, scanAreas.Count, completedAreas, allResults.Count);',
    '',
    '            try',
    '            {',
    '                var results = await Task.Run(() =>',
    '                    area.AreaType == ScanAreaType.FileSystem',
    '                        ? ScanFileSystem(area, searchTerms)',
    '                        : ScanRegistry(area, searchTerms), cancellationToken);',
    '',
    '                if (results.Count > 0)',
    '                {',
    '                    _logger.Info("  " + area.Name + ": " + results.Count + " Rest(e)");',
    '                    allResults.AddRange(results);',
    '                }',
    '            }',
    '            catch (Exception ex) when (ex is not OperationCanceledException)',
    '            {',
    '                _logger.Warning("  " + area.Name + ": " + ex.Message);',
    '            }',
    '            completedAreas++;',
    '        }',
    '',
    '        var sorted = allResults',
    '            .OrderByDescending(r => r.ConfidenceScore)',
    '            .ThenBy(r => r.ItemType)',
    '            .ThenBy(r => r.FullPath, StringComparer.OrdinalIgnoreCase).ToList();',
    '',
    '        foreach (var item in sorted)',
    '            item.IsSelectedForDeletion = item.ConfidenceScore >= 0.5;',
    '',
    '        _logger.Info("Scan fertig: " + sorted.Count + " Reste gefunden");',
    '        return sorted.AsReadOnly();',
    '    }',
    '',
    '    private List<string> BuildSearchTerms(InstalledProgram program)',
    '    {',
    '        var terms = new HashSet<string>(StringComparer.OrdinalIgnoreCase);',
    '        if (!string.IsNullOrEmpty(program.DisplayName))',
    '        {',
    '            string cleanName = CleanDisplayName(program.DisplayName);',
    '            if (cleanName.Length >= 3) terms.Add(cleanName);',
    '            foreach (string word in cleanName.Split(new[] { '' '', ''-'', ''_'', ''.'' }, StringSplitOptions.RemoveEmptyEntries))',
    '            {',
    '                if (word.Length >= 3 && !StopWords.Contains(word) && !word.All(c => char.IsDigit(c) || c == ''.''))',
    '                    terms.Add(word);',
    '            }',
    '        }',
    '        if (!string.IsNullOrEmpty(program.Publisher))',
    '        {',
    '            foreach (string word in program.Publisher.Split(new[] { '' '', '','' }, StringSplitOptions.RemoveEmptyEntries))',
    '            {',
    '                if (word.Length >= 3 && !StopWords.Contains(word)) terms.Add(word);',
    '            }',
    '        }',
    '        if (!string.IsNullOrEmpty(program.MsiProductCode)) terms.Add(program.MsiProductCode);',
    '        return terms.ToList();',
    '    }',
    '',
    '    private static string CleanDisplayName(string name)',
    '    {',
    '        string cleaned = name;',
    '        int paren = cleaned.IndexOf(''('');',
    '        if (paren > 0) cleaned = cleaned.Substring(0, paren);',
    '        cleaned = Regex.Replace(cleaned, @"\s+v?\d+[\.\d]*\s*$", "");',
    '        return cleaned.Trim();',
    '    }',
    '',
    '    private List<ScanArea> BuildScanAreas(InstalledProgram program)',
    '    {',
    '        var areas = new List<ScanArea>();',
    '        if (!string.IsNullOrEmpty(program.InstallLocation) && Directory.Exists(program.InstallLocation))',
    '            areas.Add(new ScanArea("Installationsordner", program.InstallLocation, ScanAreaType.FileSystem, ResidualDetectionSource.InstallPath));',
    '',
    '        string pf = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles);',
    '        string pfx86 = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86);',
    '        areas.Add(new ScanArea("Program Files", pf, ScanAreaType.FileSystem, ResidualDetectionSource.NameMatch));',
    '        if (pf != pfx86)',
    '            areas.Add(new ScanArea("Program Files (x86)", pfx86, ScanAreaType.FileSystem, ResidualDetectionSource.NameMatch));',
    '        areas.Add(new ScanArea("AppData Roaming", Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), ScanAreaType.FileSystem, ResidualDetectionSource.AppDataScan));',
    '        areas.Add(new ScanArea("AppData Local", Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), ScanAreaType.FileSystem, ResidualDetectionSource.AppDataScan));',
    '        areas.Add(new ScanArea("ProgramData", Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), ScanAreaType.FileSystem, ResidualDetectionSource.ProgramDataScan));',
    '        areas.Add(new ScanArea("Temp", Path.GetTempPath(), ScanAreaType.FileSystem, ResidualDetectionSource.TempScan));',
    '        areas.Add(new ScanArea("Registry HKCU", @"HKEY_CURRENT_USER\SOFTWARE", ScanAreaType.Registry, ResidualDetectionSource.RegistryScan));',
    '        areas.Add(new ScanArea("Registry HKLM", @"HKEY_LOCAL_MACHINE\SOFTWARE", ScanAreaType.Registry, ResidualDetectionSource.RegistryScan));',
    '        return areas;',
    '    }',
    '',
    '    private List<ResidualItem> ScanFileSystem(ScanArea area, List<string> searchTerms)',
    '    {',
    '        var results = new List<ResidualItem>();',
    '        if (!Directory.Exists(area.BasePath) || IsProtectedPath(area.BasePath)) return results;',
    '',
    '        if (area.Source == ResidualDetectionSource.InstallPath)',
    '        {',
    '            try { results.Add(CreateDirItem(area.BasePath, 1.0, "Installationsordner existiert noch", area.Source)); } catch { }',
    '            return results;',
    '        }',
    '',
    '        try',
    '        {',
    '            foreach (string dir in Directory.GetDirectories(area.BasePath))',
    '            {',
    '                if (IsProtectedPath(dir)) continue;',
    '                string dirName = Path.GetFileName(dir);',
    '                double score = CalculateScore(dirName, searchTerms);',
    '                if (score >= 0.5)',
    '                {',
    '                    try { results.Add(CreateDirItem(dir, score, "Ordnername stimmt ueberein (Score: " + score.ToString("P0") + ")", area.Source)); } catch { }',
    '                }',
    '            }',
    '        }',
    '        catch (UnauthorizedAccessException) { }',
    '        catch (Exception ex) { _logger.Debug("Scan-Fehler: " + area.BasePath + " - " + ex.Message); }',
    '        return results;',
    '    }',
    '',
    '    private static ResidualItem CreateDirItem(string path, double score, string reason, ResidualDetectionSource source)',
    '    {',
    '        long size = 0;',
    '        try { size = new DirectoryInfo(path).EnumerateFiles("*", SearchOption.AllDirectories).Sum(f => { try { return f.Length; } catch { return 0L; } }); } catch { }',
    '        return new ResidualItem',
    '        {',
    '            Id = Guid.NewGuid().ToString("N"), FullPath = path, ItemType = ResidualItemType.Directory,',
    '            SizeInBytes = size, ConfidenceScore = score, DetectionReason = reason,',
    '            DetectionSource = source, IsSelectedForDeletion = score >= 0.5',
    '        };',
    '    }',
    '',
    '    private List<ResidualItem> ScanRegistry(ScanArea area, List<string> searchTerms)',
    '    {',
    '        var results = new List<ResidualItem>();',
    '        if (IsProtectedRegistry(area.BasePath)) return results;',
    '        try',
    '        {',
    '            var parsed = ParseRegistryPath(area.BasePath);',
    '            if (parsed.Hive is null) return results;',
    '            using var baseKey = RegistryKey.OpenBaseKey(parsed.Hive.Value, RegistryView.Default);',
    '            using var searchKey = baseKey.OpenSubKey(parsed.SubPath);',
    '            if (searchKey is null) return results;',
    '',
    '            foreach (string subKeyName in searchKey.GetSubKeyNames())',
    '            {',
    '                string fullPath = area.BasePath + "\\" + subKeyName;',
    '                if (IsProtectedRegistry(fullPath)) continue;',
    '                double score = CalculateScore(subKeyName, searchTerms);',
    '                if (score >= 0.6)',
    '                {',
    '                    results.Add(new ResidualItem',
    '                    {',
    '                        Id = Guid.NewGuid().ToString("N"), FullPath = fullPath,',
    '                        ItemType = ResidualItemType.RegistryKey, ConfidenceScore = score,',
    '                        DetectionReason = "Registry-Key stimmt ueberein (Score: " + score.ToString("P0") + ")",',
    '                        DetectionSource = ResidualDetectionSource.RegistryScan, IsSelectedForDeletion = score >= 0.6',
    '                    });',
    '                }',
    '            }',
    '        }',
    '        catch (System.Security.SecurityException) { }',
    '        catch (Exception ex) { _logger.Debug("Registry-Fehler: " + area.BasePath + " - " + ex.Message); }',
    '        return results;',
    '    }',
    '',
    '    private static double CalculateScore(string name, List<string> searchTerms)',
    '    {',
    '        if (string.IsNullOrWhiteSpace(name) || searchTerms.Count == 0) return 0.0;',
    '        double best = 0.0;',
    '        foreach (string term in searchTerms)',
    '        {',
    '            if (term.Length < 3) continue;',
    '            if (name.Equals(term, StringComparison.OrdinalIgnoreCase)) return 1.0;',
    '            if (name.Contains(term, StringComparison.OrdinalIgnoreCase))',
    '            {',
    '                double ratio = (double)term.Length / name.Length;',
    '                best = Math.Max(best, 0.5 + (ratio * 0.5));',
    '            }',
    '        }',
    '        return best;',
    '    }',
    '',
    '    private static bool IsProtectedPath(string path) =>',
    '        ProtectedPaths.Any(p => path.StartsWith(p, StringComparison.OrdinalIgnoreCase));',
    '    private static bool IsProtectedRegistry(string path) =>',
    '        ProtectedRegistryPrefixes.Any(p => path.StartsWith(p, StringComparison.OrdinalIgnoreCase));',
    '',
    '    private static (RegistryHive? Hive, string SubPath) ParseRegistryPath(string path)',
    '    {',
    '        if (path.StartsWith(@"HKEY_CURRENT_USER\", StringComparison.OrdinalIgnoreCase))',
    '            return (RegistryHive.CurrentUser, path.Substring(18));',
    '        if (path.StartsWith(@"HKEY_LOCAL_MACHINE\", StringComparison.OrdinalIgnoreCase))',
    '            return (RegistryHive.LocalMachine, path.Substring(19));',
    '        return (null, path);',
    '    }',
    '',
    '    private void ReportProgress(string area, string path, int total, int completed, int found)',
    '    {',
    '        ProgressChanged?.Invoke(this, new ScanProgressEventArgs',
    '        { CurrentAreaName = area, CurrentPath = path, TotalAreas = total, CompletedAreas = completed, ItemsFoundSoFar = found });',
    '    }',
    '}',
    '',
    'internal sealed class ScanArea',
    '{',
    '    public string Name { get; }',
    '    public string BasePath { get; }',
    '    public ScanAreaType AreaType { get; }',
    '    public ResidualDetectionSource Source { get; }',
    '    public ScanArea(string name, string basePath, ScanAreaType areaType, ResidualDetectionSource source)',
    '    { Name = name; BasePath = basePath; AreaType = areaType; Source = source; }',
    '}',
    '',
    'internal enum ScanAreaType { FileSystem, Registry }'
)

# Anführungszeichen in den Zeilen korrigieren
for ($i = 0; $i -lt $lines.Length; $i++) {
    $lines[$i] = $lines[$i] -replace "''", "'"
}

# Datei schreiben
$content = $lines -join "`r`n"
[System.IO.File]::WriteAllText($targetFile, $content, [System.Text.Encoding]::UTF8)

Write-Host "ResidualAnalysisEngine.cs komplett neu geschrieben!" -ForegroundColor Green